# Generated by Django 6.0.6 on 2026-09-28 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turnos', '0010_turno_asistencia_confirmada_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('revocada', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DispositivoPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('plataforma', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movil.sesionmovil')),
            ],
        ),
        migrations.CreateModel(
            name='RecordatorioTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_turno', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado por Expo'), ('ENTREGADO', 'Aceptado por FCM/APNs'), ('ERROR', 'Error'), ('OMITIDO', 'Omitido')], default='PENDIENTE', max_length=15)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('proximo_intento', models.DateTimeField()),
                ('ticket', models.CharField(blank=True, max_length=128)),
                ('error_codigo', models.CharField(blank=True, max_length=80)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movil.dispositivopush')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.turno')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('turno', 'dispositivo', 'fecha_turno'), name='recordatorio_turno_dispositivo_fecha')],
            },
        ),
    ]
