# Generated by Django 5.2.4 on 2025-08-09 01:11

from django.db import migrations, models
import django.db.models.deletion


def create_users_for_existing_medicos(apps, schema_editor):
    """
    Create User objects for existing Medico records and link them
    """
    Medico = apps.get_model('medicos', 'Medico')
    User = apps.get_model('usuarios', 'User')
    
    for medico in Medico.objects.all():
        # Create a new user with the existing medico data
        username = f"medico_{medico.id}"
        user = User.objects.create_user(
            username=username,
            first_name=medico.nombre,
            last_name=medico.apellido,
            email=medico.email or f"{username}@example.com",
            password='changeme123',  # Default password that should be changed
            rol='medico'  # Set the role as medico
        )
        
        # Link the medico to the new user
        medico.user = user
        medico.save()


def reverse_create_users(apps, schema_editor):
    """
    Reverse operation: delete created users
    """
    Medico = apps.get_model('medicos', 'Medico')
    User = apps.get_model('usuarios', 'User')
    
    # Delete users created for medicos
    for medico in Medico.objects.all():
        if medico.user:
            medico.user.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_auto_20250808_1312'),
        ('usuarios', '__first__'),  # Ensure usuarios app is available
    ]

    operations = [
        # Step 1: Add the user field as nullable
        migrations.AddField(
            model_name='medico',
            name='user',
            field=models.OneToOneField(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='medico',
                to='usuarios.user',
                verbose_name='Usuario del Sistema'
            ),
        ),
        
        # Step 2: Create users and link them to existing medicos
        migrations.RunPython(create_users_for_existing_medicos, reverse_create_users),
        
        # Step 3: Make the user field non-nullable
        migrations.AlterField(
            model_name='medico',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='medico',
                to='usuarios.user',
                verbose_name='Usuario del Sistema'
            ),
        ),
        
        # Step 4: Remove the old fields
        migrations.RemoveField(
            model_name='medico',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='email',
        ),
        
        # Step 5: Update the ordering
        migrations.AlterModelOptions(
            name='medico',
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
