# Generated by Django 5.2.4 on 2025-08-09 01:14

from django.db import migrations


def create_sample_data(apps, schema_editor):
    """
    Create sample data for medicos and especialidades
    """
    Especialidad = apps.get_model('medicos', 'Especialidad')
    Medico = apps.get_model('medicos', 'Medico')
    User = apps.get_model('usuarios', 'User')
    
    # Create especialidades
    especialidades = [
        {'nombre': 'Cardiología', 'descripcion': 'Especialidad médica que se encarga del estudio, diagnóstico y tratamiento de las enfermedades del corazón y del sistema circulatorio.'},
        {'nombre': 'Dermatología', 'descripcion': 'Especialidad médica que se encarga del estudio, diagnóstico y tratamiento de las enfermedades de la piel.'},
        {'nombre': 'Endocrinología', 'descripcion': 'Especialidad médica que se encarga del estudio, diagnóstico y tratamiento de las enfermedades del sistema endocrino.'},
        {'nombre': 'Gastroenterología', 'descripcion': 'Especialidad médica que se encarga del estudio, diagnóstico y tratamiento de las enfermedades del aparato digestivo.'},
        {'nombre': 'Neurología', 'descripcion': 'Especialidad médica que se encarga del estudio, diagnóstico y tratamiento de las enfermedades del sistema nervioso.'},
        {'nombre': 'Oftalmología', 'descripcion': 'Especialidad médica que se encarga del estudio, diagnóstico y tratamiento de las enfermedades de los ojos.'},
        {'nombre': 'Ortopedia', 'descripcion': 'Especialidad médica que se encarga del estudio, diagnóstico y tratamiento de las enfermedades del sistema musculoesquelético.'},
        {'nombre': 'Pediatría', 'descripcion': 'Especialidad médica que se encarga del estudio, diagnóstico y tratamiento de las enfermedades de los niños.'},
        {'nombre': 'Psiquiatría', 'descripcion': 'Especialidad médica que se encarga del estudio, diagnóstico y tratamiento de las enfermedades mentales.'},
        {'nombre': 'Radiología', 'descripcion': 'Especialidad médica que se encarga del estudio, diagnóstico y tratamiento mediante el uso de imágenes médicas.'},
    ]
    
    for esp_data in especialidades:
        especialidad, created = Especialidad.objects.get_or_create(
            nombre=esp_data['nombre'],
            defaults={'descripcion': esp_data['descripcion']}
        )
    
    # Create sample medicos
    medicos_data = [
        {
            'username': 'dr.garcia',
            'first_name': 'Carlos',
            'last_name': 'García',
            'email': 'carlos.garcia@hospital.com',
            'matricula': 'MP12345',
            'especialidad_nombre': 'Cardiología'
        },
        {
            'username': 'dra.rodriguez',
            'first_name': 'Ana',
            'last_name': 'Rodríguez',
            'email': 'ana.rodriguez@hospital.com',
            'matricula': 'MP12346',
            'especialidad_nombre': 'Dermatología'
        },
        {
            'username': 'dr.lopez',
            'first_name': 'Miguel',
            'last_name': 'López',
            'email': 'miguel.lopez@hospital.com',
            'matricula': 'MP12347',
            'especialidad_nombre': 'Endocrinología'
        },
        {
            'username': 'dra.martinez',
            'first_name': 'Laura',
            'last_name': 'Martínez',
            'email': 'laura.martinez@hospital.com',
            'matricula': 'MP12348',
            'especialidad_nombre': 'Gastroenterología'
        },
        {
            'username': 'dr.gonzalez',
            'first_name': 'Roberto',
            'last_name': 'González',
            'email': 'roberto.gonzalez@hospital.com',
            'matricula': 'MP12349',
            'especialidad_nombre': 'Neurología'
        },
    ]
    
    for med_data in medicos_data:
        # Create user
        user, created = User.objects.get_or_create(
            username=med_data['username'],
            defaults={
                'first_name': med_data['first_name'],
                'last_name': med_data['last_name'],
                'email': med_data['email'],
                'password': 'pbkdf2_sha256$600000$changeme123$changeme123',  # This is a placeholder
                'rol': 'medico'
            }
        )
        
        if created:
            # Set a proper password (using the raw field in migrations)
            from django.contrib.auth.hashers import make_password
            user.password = make_password('changeme123')
            user.save()
        
        # Get especialidad
        especialidad = Especialidad.objects.get(nombre=med_data['especialidad_nombre'])
        
        # Create medico
        medico, created = Medico.objects.get_or_create(
            user=user,
            defaults={
                'matricula': med_data['matricula'],
                'especialidad': especialidad,
                'areas_interes_ia': f'Áreas de interés en {especialidad.nombre}'
            }
        )


def reverse_sample_data(apps, schema_editor):
    """
    Remove sample data
    """
    Medico = apps.get_model('medicos', 'Medico')
    User = apps.get_model('usuarios', 'User')
    Especialidad = apps.get_model('medicos', 'Especialidad')
    
    # Delete medicos and their users
    for medico in Medico.objects.all():
        if medico.user:
            medico.user.delete()
    
    # Delete especialidades
    Especialidad.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_auto_20250809_0111'),
        ('usuarios', '__first__'),
    ]

    operations = [
        migrations.RunPython(create_sample_data, reverse_sample_data),
    ]
