# Generated by Django 5.2.4 on 2025-08-28 19:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicos", "0004_auto_20250809_0114"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisponibilidadMedico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.IntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ]
                    ),
                ),
                ("hora_inicio", models.TimeField(default=datetime.time(8, 0))),
                ("hora_fin", models.TimeField(default=datetime.time(17, 0))),
                ("duracion_slot_min", models.PositiveIntegerField(default=30)),
                ("activo", models.BooleanField(default=True)),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disponibilidades",
                        to="medicos.medico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disponibilidad de Médico",
                "verbose_name_plural": "Disponibilidades de Médico",
                "ordering": ["medico", "dia_semana", "hora_inicio"],
                "unique_together": {
                    ("medico", "dia_semana", "hora_inicio", "hora_fin")
                },
            },
        ),
        migrations.CreateModel(
            name="ExcepcionMedico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("BLOQUEO", "No atiende"),
                            ("AJUSTE", "Ajuste horario"),
                        ],
                        default="BLOQUEO",
                        max_length=10,
                    ),
                ),
                ("hora_inicio", models.TimeField(blank=True, null=True)),
                ("hora_fin", models.TimeField(blank=True, null=True)),
                ("motivo", models.CharField(blank=True, max_length=200)),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excepciones",
                        to="medicos.medico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Excepción de Médico",
                "verbose_name_plural": "Excepciones de Médico",
                "ordering": ["medico", "-fecha"],
                "unique_together": {
                    ("medico", "fecha", "tipo", "hora_inicio", "hora_fin")
                },
            },
        ),
    ]
