# Generated by Django 6.0.6 on 2026-09-28 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0006_medico_nombre_apellido_optional_user'),
        ('turnos', '0009_tipo_atencion_guardia'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadmedico',
            name='recurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='horarios_medicos', to='turnos.recurso'),
        ),
        migrations.AddField(
            model_name='disponibilidadmedico',
            name='tipo',
            field=models.CharField(choices=[('CONSULTA', 'Consulta'), ('ESTUDIO', 'Estudio')], default='CONSULTA', max_length=10),
        ),
        migrations.AlterField(
            model_name='disponibilidadmedico',
            name='duracion_slot_min',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
