# Generated by Django 5.2.4 on 2025-08-06 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("historias_clinicas", "0001_initial"),
        ("medicos", "0001_initial"),
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PanelExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre del Panel"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Precio",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Panel de Examen",
                "verbose_name_plural": "Paneles de Exámenes",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre del Examen"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Precio",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Tipo de Examen",
                "verbose_name_plural": "Tipos de Exámenes",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="SolicitudExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Número de Solicitud",
                    ),
                ),
                (
                    "fecha_solicitud",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Solicitud"
                    ),
                ),
                (
                    "fecha_entrega",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Entrega"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En Proceso"),
                            ("COMPLETADO", "Completado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Total"
                    ),
                ),
                (
                    "consulta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="historias_clinicas.consulta",
                        verbose_name="Consulta",
                    ),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="medicos.medico",
                        verbose_name="Médico",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pacientes.paciente",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "paneles",
                    models.ManyToManyField(
                        blank=True, to="laboratorio.panelexamen", verbose_name="Paneles"
                    ),
                ),
                (
                    "examenes_individuales",
                    models.ManyToManyField(
                        blank=True,
                        to="laboratorio.tipoexamen",
                        verbose_name="Exámenes Individuales",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Examen",
                "verbose_name_plural": "Solicitudes de Exámenes",
                "ordering": ["-fecha_solicitud"],
            },
        ),
        migrations.AddField(
            model_name="panelexamen",
            name="examenes",
            field=models.ManyToManyField(
                to="laboratorio.tipoexamen", verbose_name="Exámenes del Panel"
            ),
        ),
        migrations.CreateModel(
            name="ResultadoExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Valor del Resultado"
                    ),
                ),
                (
                    "valor_normal",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Valor Normal"
                    ),
                ),
                (
                    "unidad",
                    models.CharField(blank=True, max_length=50, verbose_name="Unidad"),
                ),
                (
                    "es_normal",
                    models.BooleanField(default=True, verbose_name="¿Es Normal?"),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "fecha_resultado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha del Resultado"
                    ),
                ),
                (
                    "tecnico",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Técnico Responsable"
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laboratorio.solicitudexamen",
                        verbose_name="Solicitud",
                    ),
                ),
                (
                    "tipo_examen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laboratorio.tipoexamen",
                        verbose_name="Tipo de Examen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado de Examen",
                "verbose_name_plural": "Resultados de Exámenes",
                "ordering": ["-fecha_resultado"],
                "unique_together": {("solicitud", "tipo_examen")},
            },
        ),
    ]
