# Generated by Django 5.2.8 on 2025-11-26 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0006_medico_nombre_apellido_optional_user'),
        ('pacientes', '0008_alter_paciente_options_paciente_apellido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Panel de Examen',
                'verbose_name_plural': 'Paneles de Examen',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('abreviatura', models.CharField(blank=True, max_length=20, null=True, verbose_name='Abreviatura')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
                ('rango_referencia_texto', models.CharField(blank=True, help_text="Para imprimir en informe (ej: '70-100 mg/dL')", max_length=255, null=True, verbose_name='Rango de Referencia (Texto)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Examen',
                'verbose_name_plural': 'Tipos de Examen',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('color_tubo', models.CharField(blank=True, help_text='Útil para UI (ej: Rojo, Azul, Verde)', max_length=50, null=True, verbose_name='Color del Tubo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Muestra',
                'verbose_name_plural': 'Tipos de Muestra',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, help_text='Generado automáticamente en formato LAB-YYYY-XXXXX', max_length=20, null=True, unique=True, verbose_name='Número de Protocolo')),
                ('medico_externo_nombre', models.CharField(blank=True, help_text='Nombre del médico para recetas en papel de médicos fuera de la clínica', max_length=200, null=True, verbose_name='Médico Externo')),
                ('origen_solicitud', models.CharField(choices=[('EMR', 'EMR (Digital)'), ('GUARDIA', 'Guardia'), ('EXTERNO_PAPEL', 'Externo (Papel)')], default='EMR', max_length=20, verbose_name='Origen de la Solicitud')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('TOMA_MUESTRA', 'Toma de Muestra'), ('EN_PROCESO', 'En Proceso'), ('VALIDADO', 'Validado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_entrega_prometida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega Prometida')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('medico_interno', models.ForeignKey(blank=True, help_text='Médico del sistema EMR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_examen', to='medicos.medico', verbose_name='Médico Interno')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_examen', to='pacientes.paciente', verbose_name='Paciente')),
                ('paneles', models.ManyToManyField(blank=True, related_name='solicitudes', to='laboratorio.panelexamen', verbose_name='Paneles de Examen')),
                ('tipos_examen', models.ManyToManyField(blank=True, related_name='solicitudes', to='laboratorio.tipoexamen', verbose_name='Tipos de Examen')),
            ],
            options={
                'verbose_name': 'Solicitud de Examen',
                'verbose_name_plural': 'Solicitudes de Examen',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_obtenido', models.CharField(help_text="Puede ser número o texto (ej: 'Positivo', 'Negativo', '120.5')", max_length=255, verbose_name='Valor Obtenido')),
                ('es_patologico', models.BooleanField(default=False, verbose_name='Es Patológico')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Validación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_validados', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='laboratorio.solicitudexamen', verbose_name='Solicitud')),
                ('tipo_examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='laboratorio.tipoexamen', verbose_name='Tipo de Examen')),
            ],
            options={
                'verbose_name': 'Resultado de Examen',
                'verbose_name_plural': 'Resultados de Examen',
                'ordering': ['tipo_examen__nombre'],
            },
        ),
        migrations.AddField(
            model_name='panelexamen',
            name='tipos_examen',
            field=models.ManyToManyField(blank=True, help_text='Exámenes que componen este panel', related_name='paneles', to='laboratorio.tipoexamen', verbose_name='Tipos de Examen'),
        ),
        migrations.AddField(
            model_name='tipoexamen',
            name='tipo_muestra_requerida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_examen', to='laboratorio.tipomuestra', verbose_name='Tipo de Muestra Requerida'),
        ),
        migrations.AddIndex(
            model_name='solicitudexamen',
            index=models.Index(fields=['estado', 'fecha_solicitud'], name='laboratorio_estado_39a08a_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudexamen',
            index=models.Index(fields=['paciente', 'estado'], name='laboratorio_pacient_c38d22_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resultadoexamen',
            unique_together={('solicitud', 'tipo_examen')},
        ),
    ]
