# Generated by Django 5.2.4 on 2025-08-06 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0001_initial"),
        ("medicos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resultadoexamen",
            name="valor",
        ),
        migrations.RemoveField(
            model_name="resultadoexamen",
            name="valor_normal",
        ),
        migrations.AddField(
            model_name="resultadoexamen",
            name="interpretacion_ia",
            field=models.TextField(blank=True, verbose_name="Interpretación IA"),
        ),
        migrations.AddField(
            model_name="resultadoexamen",
            name="validado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="medicos.medico",
                verbose_name="Validado por",
            ),
        ),
        migrations.AddField(
            model_name="resultadoexamen",
            name="valor_normal_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="Valor Normal Máximo",
            ),
        ),
        migrations.AddField(
            model_name="resultadoexamen",
            name="valor_normal_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="Valor Normal Mínimo",
            ),
        ),
        migrations.AddField(
            model_name="resultadoexamen",
            name="valor_normal_texto",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Valor Normal (Texto)"
            ),
        ),
        migrations.AddField(
            model_name="resultadoexamen",
            name="valor_numerico",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="Valor Numérico",
            ),
        ),
        migrations.AddField(
            model_name="resultadoexamen",
            name="valor_texto",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Valor Texto"
            ),
        ),
    ]
