# Generated by Django 5.2.4 on 2026-05-04 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_alter_resultadoexamen_valor_obtenido'),
        ('pacientes', '0009_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Área de laboratorio',
                'verbose_name_plural': 'Áreas de laboratorio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoContenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('color', models.CharField(blank=True, default='', max_length=50, verbose_name='Color')),
                ('volumen_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Volumen (ml)')),
                ('aditivo', models.CharField(blank=True, default='', max_length=100, verbose_name='Aditivo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de contenedor',
                'verbose_name_plural': 'Tipos de contenedor',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.CharField(blank=True, help_text='Generado automáticamente si se deja vacío (MUE-YYYY-NNNNNN).', max_length=32, null=True, unique=True, verbose_name='Código de barras')),
                ('estado', models.CharField(choices=[('PENDIENTE_TOMA', 'Pendiente de toma'), ('TOMADA', 'Tomada'), ('RECIBIDA', 'Recibida en laboratorio'), ('EN_PROCESO', 'En proceso'), ('RECHAZADA', 'Rechazada'), ('CONSERVADA', 'En conservación'), ('DESCARTADA', 'Descartada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE_TOMA', max_length=20, verbose_name='Estado')),
                ('fecha_toma', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de toma')),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de recepción')),
                ('fecha_rechazo', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de rechazo')),
                ('motivo_rechazo', models.TextField(blank=True, default='', verbose_name='Motivo de rechazo')),
                ('ubicacion_actual', models.CharField(blank=True, default='', max_length=255, verbose_name='Ubicación actual')),
                ('fecha_conservacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de conservación')),
                ('fecha_descarte', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de descarte')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descartada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestras_descartadas', to=settings.AUTH_USER_MODEL, verbose_name='Descartada por')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='muestras_lims', to='pacientes.paciente', verbose_name='Paciente')),
                ('rechazada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestras_rechazadas', to=settings.AUTH_USER_MODEL, verbose_name='Rechazada por')),
                ('recibida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestras_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Recibida por')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='muestras', to='laboratorio.solicitudexamen', verbose_name='Solicitud')),
                ('tipo_muestra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='muestras', to='laboratorio.tipomuestra', verbose_name='Tipo de muestra (catálogo)')),
                ('tomada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestras_tomadas', to=settings.AUTH_USER_MODEL, verbose_name='Tomada por')),
                ('tipo_contenedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestras', to='laboratorio.tipocontenedor', verbose_name='Tipo de contenedor')),
            ],
            options={
                'verbose_name': 'Muestra',
                'verbose_name_plural': 'Muestras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventoMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREADA', 'Creada'), ('TOMADA', 'Tomada'), ('RECIBIDA', 'Recibida'), ('EN_PROCESO', 'En proceso'), ('RECHAZADA', 'Rechazada'), ('CONSERVADA', 'Conservada'), ('DESCARTADA', 'Descartada'), ('CANCELADA', 'Cancelada'), ('ACTUALIZADA', 'Actualización administrativa')], max_length=32, verbose_name='Acción')),
                ('estado_anterior', models.CharField(blank=True, default='', max_length=32, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(blank=True, default='', max_length=32, verbose_name='Estado nuevo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('request_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Request ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_muestra', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='laboratorio.muestra', verbose_name='Muestra')),
            ],
            options={
                'verbose_name': 'Evento de muestra',
                'verbose_name_plural': 'Eventos de muestra',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['muestra', '-fecha'], name='laboratorio_muestra_8e8308_idx')],
            },
        ),
        migrations.CreateModel(
            name='SeccionLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secciones', to='laboratorio.arealaboratorio', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Sección de laboratorio',
                'verbose_name_plural': 'Secciones de laboratorio',
                'ordering': ['area', 'nombre'],
                'indexes': [models.Index(fields=['area', 'activo'], name='laboratorio_area_id_304332_idx')],
                'unique_together': {('area', 'codigo')},
            },
        ),
        migrations.AddIndex(
            model_name='muestra',
            index=models.Index(fields=['solicitud', 'estado'], name='laboratorio_solicit_a38e82_idx'),
        ),
        migrations.AddIndex(
            model_name='muestra',
            index=models.Index(fields=['paciente', 'estado'], name='laboratorio_pacient_bb98a2_idx'),
        ),
        migrations.AddIndex(
            model_name='muestra',
            index=models.Index(fields=['estado', 'created_at'], name='laboratorio_estado_117c89_idx'),
        ),
        migrations.AddIndex(
            model_name='muestra',
            index=models.Index(fields=['tipo_muestra'], name='laboratorio_tipo_mu_fa4667_idx'),
        ),
        migrations.AddIndex(
            model_name='muestra',
            index=models.Index(fields=['fecha_toma'], name='laboratorio_fecha_t_592e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='muestra',
            index=models.Index(fields=['fecha_recepcion'], name='laboratorio_fecha_r_b97461_idx'),
        ),
    ]
