# Generated by Django 5.2.4 on 2026-05-05 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_lims_b0_b1_muestras'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoexamen',
            name='muestra',
            field=models.ForeignKey(blank=True, help_text='Muestra física asociada (opcional; compatibilidad con resultados históricos sin muestra).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='laboratorio.muestra', verbose_name='Muestra'),
        ),
    ]
