# Generated by Django 5.2.4 on 2026-05-13 21:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0004_lims_b2_resultado_muestra'),
        ('pacientes', '0009_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('tipo', models.CharField(blank=True, default='', max_length=50, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medio de cultivo',
                'verbose_name_plural': 'Medios de cultivo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstudioMicrobiologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, help_text='Generado automáticamente si se deja vacío (MIC-YYYY-NNNNNN).', max_length=32, null=True, unique=True, verbose_name='Número de estudio')),
                ('tipo_estudio', models.CharField(choices=[('CULTIVO_RUTINA', 'Cultivo de rutina'), ('UROCULTIVO', 'Urocultivo'), ('HEMOCULTIVO', 'Hemocultivo'), ('COPROCULTIVO', 'Coprocultivo'), ('CULTIVO_HERIDA', 'Cultivo de herida'), ('OTRO', 'Otro')], default='CULTIVO_RUTINA', max_length=32, verbose_name='Tipo de estudio')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDO', 'Recibido'), ('SEMBRADO', 'Sembrado'), ('LECTURA_PRELIMINAR', 'Lectura preliminar'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=32, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('motivo_cancelacion', models.TextField(blank=True, default='', verbose_name='Motivo de cancelación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_microbiologia_cancelados', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado por')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudios_microbiologia', to='laboratorio.muestra', verbose_name='Muestra')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudios_microbiologia', to='pacientes.paciente', verbose_name='Paciente')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_microbiologia_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudios_microbiologia', to='laboratorio.solicitudexamen', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Estudio de microbiología',
                'verbose_name_plural': 'Estudios de microbiología',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiembraMicrobiologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_siembra', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de siembra')),
                ('condicion_incubacion', models.CharField(blank=True, default='', max_length=120, verbose_name='Condición de incubación')),
                ('temperatura_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura (°C)')),
                ('atmosfera', models.CharField(blank=True, default='', max_length=80, verbose_name='Atmósfera')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('SEMBRADA', 'Sembrada'), ('CANCELADA', 'Cancelada')], default='SEMBRADA', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siembras', to='laboratorio.estudiomicrobiologia', verbose_name='Estudio')),
                ('medio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siembras', to='laboratorio.mediocultivo', verbose_name='Medio de cultivo')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siembras_microbiologia', to='laboratorio.muestra', verbose_name='Muestra')),
                ('sembrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siembras_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Sembrado por')),
            ],
            options={
                'verbose_name': 'Siembra microbiológica',
                'verbose_name_plural': 'Siembras microbiológicas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LecturaCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lectura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de lectura')),
                ('horas_incubacion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas de incubación')),
                ('crecimiento', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('SIN_DESARROLLO', 'Sin desarrollo'), ('ESCASO', 'Escaso'), ('MODERADO', 'Moderado'), ('ABUNDANTE', 'Abundante'), ('MIXTO', 'Mixto')], default='PENDIENTE', max_length=20, verbose_name='Crecimiento')),
                ('descripcion_colonias', models.TextField(blank=True, default='', verbose_name='Descripción colonias')),
                ('tincion_gram', models.TextField(blank=True, default='', verbose_name='Tinción de Gram')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('es_preliminar', models.BooleanField(default=False, verbose_name='Lectura preliminar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturas', to='laboratorio.estudiomicrobiologia', verbose_name='Estudio')),
                ('leido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Leído por')),
                ('siembra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturas', to='laboratorio.siembramicrobiologia', verbose_name='Siembra')),
            ],
            options={
                'verbose_name': 'Lectura de cultivo',
                'verbose_name_plural': 'Lecturas de cultivo',
                'ordering': ['-fecha_lectura', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='estudiomicrobiologia',
            index=models.Index(fields=['solicitud', 'estado'], name='laboratorio_solicit_03e088_idx'),
        ),
        migrations.AddIndex(
            model_name='estudiomicrobiologia',
            index=models.Index(fields=['muestra', 'estado'], name='laboratorio_muestra_5757a7_idx'),
        ),
        migrations.AddIndex(
            model_name='estudiomicrobiologia',
            index=models.Index(fields=['paciente', 'estado'], name='laboratorio_pacient_18c612_idx'),
        ),
        migrations.AddIndex(
            model_name='estudiomicrobiologia',
            index=models.Index(fields=['estado', 'created_at'], name='laboratorio_estado_a1e737_idx'),
        ),
        migrations.AddIndex(
            model_name='estudiomicrobiologia',
            index=models.Index(fields=['fecha_inicio'], name='laboratorio_fecha_i_897ae6_idx'),
        ),
        migrations.AddIndex(
            model_name='siembramicrobiologia',
            index=models.Index(fields=['estudio', 'estado'], name='laboratorio_estudio_3a2e87_idx'),
        ),
        migrations.AddIndex(
            model_name='siembramicrobiologia',
            index=models.Index(fields=['medio'], name='laboratorio_medio_i_bf5f30_idx'),
        ),
        migrations.AddIndex(
            model_name='siembramicrobiologia',
            index=models.Index(fields=['fecha_siembra'], name='laboratorio_fecha_s_1f74b3_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturacultivo',
            index=models.Index(fields=['siembra', '-fecha_lectura'], name='laboratorio_siembra_d11710_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturacultivo',
            index=models.Index(fields=['estudio', '-fecha_lectura'], name='laboratorio_estudio_83dd2a_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturacultivo',
            index=models.Index(fields=['crecimiento'], name='laboratorio_crecimi_c50b3b_idx'),
        ),
    ]
