# Generated by Django 5.2.4 on 2026-05-13 22:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0005_lims_b3_1_microbiologia_base'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiomicrobiologia',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDO', 'Recibido'), ('SEMBRADO', 'Sembrado'), ('LECTURA_PRELIMINAR', 'Lectura preliminar'), ('IDENTIFICACION', 'Identificación'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=32, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='Microorganismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('genero', models.CharField(blank=True, default='', max_length=120, verbose_name='Género')),
                ('especie', models.CharField(blank=True, default='', max_length=120, verbose_name='Especie')),
                ('grupo', models.CharField(blank=True, default='', max_length=80, verbose_name='Grupo')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Microorganismo',
                'verbose_name_plural': 'Microorganismos',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['activo', 'nombre'], name='laboratorio_activo_0ca228_idx'), models.Index(fields=['genero', 'especie'], name='laboratorio_genero_e33444_idx')],
            },
        ),
        migrations.CreateModel(
            name='AisladoMicrobiologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('SOSPECHADO', 'Sospechado'), ('IDENTIFICADO', 'Identificado'), ('DESCARTADO', 'Descartado')], default='SOSPECHADO', max_length=20, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('cantidad', models.CharField(blank=True, default='', max_length=80, verbose_name='Cantidad')),
                ('significancia', models.CharField(choices=[('NO_DEFINIDA', 'No definida'), ('CONTAMINANTE', 'Contaminante'), ('FLORA_HABITUAL', 'Flora habitual'), ('SIGNIFICATIVO', 'Significativo'), ('CRITICO', 'Crítico')], default='NO_DEFINIDA', max_length=20, verbose_name='Significancia')),
                ('requiere_antibiograma', models.BooleanField(default=False, help_text='Marcado para flujo futuro B3.3; en B3.2 no dispara creación automática.', verbose_name='Requiere antibiograma')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('fecha_descarte', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de descarte')),
                ('motivo_descarte', models.TextField(blank=True, default='', verbose_name='Motivo de descarte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aislados_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('descartado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aislados_descartados', to=settings.AUTH_USER_MODEL, verbose_name='Descartado por')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aislados', to='laboratorio.estudiomicrobiologia', verbose_name='Estudio')),
                ('lectura_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aislados', to='laboratorio.lecturacultivo', verbose_name='Lectura de origen')),
                ('microorganismo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aislados', to='laboratorio.microorganismo', verbose_name='Microorganismo')),
            ],
            options={
                'verbose_name': 'Aislado microbiológico',
                'verbose_name_plural': 'Aislados microbiológicos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdentificacionMicroorganismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(blank=True, default='', max_length=120, verbose_name='Método')),
                ('resultado', models.TextField(blank=True, default='', verbose_name='Resultado')),
                ('confianza', models.DecimalField(blank=True, decimal_places=2, help_text='Valor entre 0 y 100; opcional.', max_digits=5, null=True, verbose_name='Confianza (%)')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aislado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identificaciones', to='laboratorio.aisladomicrobiologico', verbose_name='Aislado')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identificaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('microorganismo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identificaciones', to='laboratorio.microorganismo', verbose_name='Microorganismo')),
            ],
            options={
                'verbose_name': 'Identificación de microorganismo',
                'verbose_name_plural': 'Identificaciones de microorganismo',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['aislado', '-fecha'], name='laboratorio_aislado_a862d9_idx'), models.Index(fields=['microorganismo'], name='laboratorio_microor_695197_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='aisladomicrobiologico',
            index=models.Index(fields=['estudio', 'estado'], name='laboratorio_estudio_8b965a_idx'),
        ),
        migrations.AddIndex(
            model_name='aisladomicrobiologico',
            index=models.Index(fields=['lectura_origen'], name='laboratorio_lectura_25a220_idx'),
        ),
        migrations.AddIndex(
            model_name='aisladomicrobiologico',
            index=models.Index(fields=['microorganismo', 'estado'], name='laboratorio_microor_081235_idx'),
        ),
        migrations.AddIndex(
            model_name='aisladomicrobiologico',
            index=models.Index(fields=['significancia'], name='laboratorio_signifi_7b562a_idx'),
        ),
    ]
