# Generated by Django 5.2.4 on 2026-05-13 23:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0006_lims_b3_2_microbiologia_aislados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiomicrobiologia',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDO', 'Recibido'), ('SEMBRADO', 'Sembrado'), ('LECTURA_PRELIMINAR', 'Lectura preliminar'), ('IDENTIFICACION', 'Identificación'), ('ANTIBIOGRAMA', 'Antibiograma'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=32, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='Antibiograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETO', 'Completo'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('metodo', models.CharField(blank=True, default='', max_length=120, verbose_name='Método')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('fecha_resultado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resultado')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('motivo_cancelacion', models.TextField(blank=True, default='', verbose_name='Motivo de cancelación')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aislado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='antibiogramas', to='laboratorio.aisladomicrobiologico', verbose_name='Aislado')),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antibiogramas_cancelados', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado por')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antibiogramas_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Antibiograma',
                'verbose_name_plural': 'Antibiogramas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Antibiotico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('familia', models.CharField(blank=True, default='', max_length=120, verbose_name='Familia')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Antibiótico',
                'verbose_name_plural': 'Antibióticos',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['activo', 'nombre'], name='laboratorio_activo_38ffb4_idx'), models.Index(fields=['familia'], name='laboratorio_familia_012f3d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResultadoAntibiotico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halo_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Halo (mm)')),
                ('mic', models.CharField(blank=True, default='', max_length=40, verbose_name='MIC')),
                ('interpretacion', models.CharField(choices=[('S', 'Sensible'), ('I', 'Intermedio'), ('R', 'Resistente'), ('SDD', 'Sensible dosis-dependiente'), ('NO_APLICA', 'No aplica')], max_length=10, verbose_name='Interpretación')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('antibiograma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='laboratorio.antibiograma', verbose_name='Antibiograma')),
                ('antibiotico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='laboratorio.antibiotico', verbose_name='Antibiótico')),
            ],
            options={
                'verbose_name': 'Resultado de antibiótico',
                'verbose_name_plural': 'Resultados de antibiótico',
                'ordering': ['antibiograma', 'antibiotico'],
            },
        ),
        migrations.AddIndex(
            model_name='antibiograma',
            index=models.Index(fields=['aislado', 'estado'], name='laboratorio_aislado_c8694f_idx'),
        ),
        migrations.AddIndex(
            model_name='antibiograma',
            index=models.Index(fields=['estado', 'created_at'], name='laboratorio_estado_a09ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='antibiograma',
            index=models.Index(fields=['fecha_inicio'], name='laboratorio_fecha_i_c5138a_idx'),
        ),
        migrations.AddIndex(
            model_name='resultadoantibiotico',
            index=models.Index(fields=['antibiograma'], name='laboratorio_antibio_9a5d86_idx'),
        ),
        migrations.AddIndex(
            model_name='resultadoantibiotico',
            index=models.Index(fields=['antibiotico'], name='laboratorio_antibio_6230f1_idx'),
        ),
        migrations.AddIndex(
            model_name='resultadoantibiotico',
            index=models.Index(fields=['interpretacion'], name='laboratorio_interpr_0a68b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='resultadoantibiotico',
            constraint=models.UniqueConstraint(fields=('antibiograma', 'antibiotico'), name='uniq_resultado_por_antibiograma_antibiotico'),
        ),
    ]
