# Generated by Django 5.2.4 on 2026-05-14 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0007_lims_b3_3_microbiologia_antibiograma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiomicrobiologia',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDO', 'Recibido'), ('SEMBRADO', 'Sembrado'), ('LECTURA_PRELIMINAR', 'Lectura preliminar'), ('IDENTIFICACION', 'Identificación'), ('ANTIBIOGRAMA', 'Antibiograma'), ('LISTO_PARA_VALIDAR', 'Listo para validar'), ('VALIDADO', 'Validado'), ('INFORMADO', 'Informado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=32, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='InformeMicrobiologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRELIMINAR', 'Preliminar'), ('FINAL', 'Final')], max_length=12, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDO', 'Emitido'), ('VALIDADO', 'Validado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=12, verbose_name='Estado')),
                ('texto', models.TextField(blank=True, default='', verbose_name='Texto del informe')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versión')),
                ('fecha_emision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de emisión')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de validación')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('motivo_anulacion', models.TextField(blank=True, default='', verbose_name='Motivo de anulación')),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de anulación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_micro_anulados', to=settings.AUTH_USER_MODEL, verbose_name='Anulado por')),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_micro_emitidos', to=settings.AUTH_USER_MODEL, verbose_name='Emitido por')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes', to='laboratorio.estudiomicrobiologia', verbose_name='Estudio')),
                ('reemplaza_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplazos', to='laboratorio.informemicrobiologia', verbose_name='Reemplaza a')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_micro_validados', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
            ],
            options={
                'verbose_name': 'Informe de microbiología',
                'verbose_name_plural': 'Informes de microbiología',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['estudio', 'tipo', 'estado'], name='laboratorio_estudio_d6f1fb_idx'), models.Index(fields=['estudio', 'estado'], name='laboratorio_estudio_cdb6a0_idx'), models.Index(fields=['tipo', 'estado'], name='laboratorio_tipo_47a47f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('tipo', 'FINAL'), models.Q(('estado', 'ANULADO'), _negated=True)), fields=('estudio',), name='uniq_informe_final_vigente_por_estudio')],
            },
        ),
    ]
