# Generated by Django 5.2.4 on 2026-05-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0009_lims_b4_1_resultados_clinicos_estructurados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventomuestra',
            name='accion',
            field=models.CharField(choices=[('CREADA', 'Creada'), ('TOMADA', 'Tomada'), ('RECIBIDA', 'Recibida'), ('EN_PROCESO', 'En proceso'), ('RECHAZADA', 'Rechazada'), ('CONSERVADA', 'Conservada'), ('DESCARTADA', 'Descartada'), ('CANCELADA', 'Cancelada'), ('CAMBIO_UBICACION', 'Cambio de ubicación'), ('ACTUALIZADA', 'Actualización administrativa')], max_length=32, verbose_name='Acción'),
        ),
    ]
