# Generated by Django 5.2.4 on 2026-05-26 03:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0010_muestras_transaccionales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventomuestra',
            name='accion',
            field=models.CharField(choices=[('CREADA', 'Creada'), ('TOMADA', 'Tomada'), ('RECIBIDA', 'Recibida'), ('EN_PROCESO', 'En proceso'), ('PROCESAMIENTO', 'Inicio de procesamiento técnico'), ('RECHAZADA', 'Rechazada'), ('CONSERVADA', 'Conservada'), ('DESCARTADA', 'Descartada'), ('CANCELADA', 'Cancelada'), ('CAMBIO_UBICACION', 'Cambio de ubicación'), ('ACTUALIZADA', 'Actualización administrativa')], max_length=32, verbose_name='Acción'),
        ),
        migrations.AddIndex(
            model_name='resultadoexamen',
            index=models.Index(fields=['muestra'], name='laboratorio_muestra_b30d7b_idx'),
        ),
        migrations.AddIndex(
            model_name='resultadoexamen',
            index=models.Index(fields=['solicitud', 'muestra'], name='laboratorio_solicit_d9ba08_idx'),
        ),
    ]
