# Generated by Django 5.2.4 on 2026-05-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0011_resultado_muestra'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoexamen',
            name='requiere_muestra',
            field=models.BooleanField(default=False, help_text='Si está activo, cargar-resultados exige muestra_id trazable para nuevas cargas/actualizaciones.', verbose_name='Requiere muestra física'),
        ),
    ]
