# Generated by Django 5.2.16 on 2026-07-26 02:24

import django.db.models.deletion
from django.db import migrations, models


def seed_micro_catalogos(apps, schema_editor):
    from laboratorio.micro_catalogos_seed import seed_catalogos_microbiologia

    seed_catalogos_microbiologia(update_existing=True)


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0033_eab_jeringas_apartes"),
        ("medicos", "0006_medico_nombre_apellido_optional_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoCultivoMicrobiologia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo", models.CharField(max_length=40, unique=True, verbose_name="Código")),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                ("descripcion", models.TextField(blank=True, default="", verbose_name="Descripción")),
                ("orden", models.PositiveSmallIntegerField(default=100, verbose_name="Orden")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tipo de cultivo microbiológico",
                "verbose_name_plural": "Tipos de cultivo microbiológico",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoMuestraMicrobiologia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo", models.CharField(max_length=40, unique=True, verbose_name="Código")),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                ("descripcion", models.TextField(blank=True, default="", verbose_name="Descripción")),
                ("orden", models.PositiveSmallIntegerField(default=100, verbose_name="Orden")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tipo de muestra microbiológica",
                "verbose_name_plural": "Tipos de muestra microbiológica",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.AddField(
            model_name="estudiomicrobiologia",
            name="medico_externo_nombre",
            field=models.CharField(blank=True, default="", max_length=200, verbose_name="Médico externo"),
        ),
        migrations.AddField(
            model_name="estudiomicrobiologia",
            name="medico_interno",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="estudios_microbiologia", to="medicos.medico", verbose_name="Médico solicitante"),
        ),
        migrations.AlterField(
            model_name="estudiomicrobiologia",
            name="muestra",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="estudios_microbiologia", to="laboratorio.muestra", verbose_name="Muestra LIMS (legado)"),
        ),
        migrations.AlterField(
            model_name="estudiomicrobiologia",
            name="solicitud",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="estudios_microbiologia", to="laboratorio.solicitudexamen", verbose_name="Solicitud LIMS (legado)"),
        ),
        migrations.AlterField(
            model_name="estudiomicrobiologia",
            name="tipo_estudio",
            field=models.CharField(choices=[("HEMOCULTIVO", "Hemocultivo"), ("UROCULTIVO", "Urocultivo"), ("COPROCULTIVO", "Coprocultivo"), ("LCR", "Cultivo de LCR"), ("LIQUIDOS_ESTERILES", "Líquidos estériles"), ("RESPIRATORIOS", "Cultivos respiratorios"), ("EXUDADOS", "Exudados"), ("HERIDAS_ABSCESOS", "Heridas / abscesos"), ("CATETERES", "Catéteres"), ("GENITALES", "Cultivos genitales"), ("HONGOS", "Hongos"), ("ANAEROBIOS", "Anaerobios"), ("MICOBACTERIAS", "Micobacterias"), ("VIGILANCIA_EPIDEMIOLOGICA", "Vigilancia epidemiológica"), ("CULTIVO_RUTINA", "Cultivo de rutina"), ("CULTIVO_HERIDA", "Cultivo de herida"), ("OTRO", "Otro")], default="UROCULTIVO", help_text="Espejo del código de tipo_cultivo para compatibilidad.", max_length=40, verbose_name="Tipo de estudio (código)"),
        ),
        migrations.AlterField(
            model_name="siembramicrobiologia",
            name="muestra",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="siembras_microbiologia", to="laboratorio.muestra", verbose_name="Muestra LIMS (legado)"),
        ),
        migrations.AddField(
            model_name="estudiomicrobiologia",
            name="tipo_cultivo",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="estudios", to="laboratorio.tipocultivomicrobiologia", verbose_name="Tipo de cultivo"),
        ),
        migrations.AddField(
            model_name="estudiomicrobiologia",
            name="tipo_muestra_micro",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="estudios", to="laboratorio.tipomuestramicrobiologia", verbose_name="Tipo de muestra"),
        ),
        migrations.RunPython(seed_micro_catalogos, migrations.RunPython.noop),
    ]
