# Generated by Django 5.2.16 on 2026-07-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0034_micro_catalogos_cultivo_muestra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiomicrobiologia',
            name='tipo_estudio',
            field=models.CharField(default='UROCULTIVO', help_text='Espejo del código de tipo_cultivo; el catálogo es la fuente de verdad.', max_length=40, verbose_name='Tipo de estudio (código)'),
        ),
        migrations.AlterField(
            model_name='resultadoexamen',
            name='es_patologico',
            field=models.BooleanField(default=False, help_text='Indica desviación respecto al rango de referencia; no implica diagnóstico clínico.', verbose_name='Fuera de rango de referencia'),
        ),
    ]
