# Generated by Django 5.2.16 on 2026-07-26 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias_clinicas', '0007_consulta_atencion'),
        ('laboratorio', '0035_actualizar_tipos_cultivo_micro'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiomicrobiologia',
            name='codigo_barra',
            field=models.CharField(blank=True, help_text='Generado al imprimir etiqueta (MICB-YYYY-NNNNNN).', max_length=32, null=True, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AddField(
            model_name='estudiomicrobiologia',
            name='consulta_hc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_microbiologia', to='historias_clinicas.consulta', verbose_name='Consulta asociada'),
        ),
        migrations.AddField(
            model_name='estudiomicrobiologia',
            name='etiquetas_impresas_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Etiquetas impresas'),
        ),
        migrations.AddField(
            model_name='estudiomicrobiologia',
            name='origen_solicitud',
            field=models.CharField(blank=True, default='', help_text='Mismos códigos que LIMS (AMBULATORIO_*, INTERNACION_*, GUARDIA, EXTERNO_*).', max_length=24, verbose_name='Origen clínico'),
        ),
    ]
