# Generated by Django 5.2.17 on 2026-09-23 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0052_labwin_micro_catalogos'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='antibiotico',
            new_name='laboratorio_origen_580188_idx',
            old_name='laboratorio_origen_ab01_idx',
        ),
        migrations.RenameIndex(
            model_name='antibiotico',
            new_name='laboratorio_requier_d5607b_idx',
            old_name='laboratorio_requier_ab02_idx',
        ),
        migrations.RenameIndex(
            model_name='fraserapidaasociacionanalisis',
            new_name='laboratorio_analisi_076078_idx',
            old_name='laboratorio_analis_ne01_idx',
        ),
        migrations.RenameIndex(
            model_name='fraserapidaasociacionanalisis',
            new_name='laboratorio_nemotec_6e582a_idx',
            old_name='laboratorio_nemote_ne02_idx',
        ),
        migrations.RenameIndex(
            model_name='fraserapidamicrobiologia',
            new_name='laboratorio_activo_e5e83a_idx',
            old_name='laboratorio_activo_fr01_idx',
        ),
        migrations.RenameIndex(
            model_name='fraserapidamicrobiologia',
            new_name='laboratorio_origen_90e1af_idx',
            old_name='laboratorio_origen_fr02_idx',
        ),
        migrations.RenameIndex(
            model_name='fraserapidamicrobiologia',
            new_name='laboratorio_categor_74658c_idx',
            old_name='laboratorio_catego_fr03_idx',
        ),
        migrations.RenameIndex(
            model_name='fraserapidamicrobiologia',
            new_name='laboratorio_requier_ddb04b_idx',
            old_name='laboratorio_requier_fr04_idx',
        ),
        migrations.RenameIndex(
            model_name='microorganismo',
            new_name='laboratorio_origen_d48f16_idx',
            old_name='laboratorio_origen_7c1a01_idx',
        ),
        migrations.RenameIndex(
            model_name='microorganismo',
            new_name='laboratorio_requier_b67047_idx',
            old_name='laboratorio_requier_8a2b01_idx',
        ),
    ]
