# Generated by Django 5.2.4 on 2026-05-24 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archivos_medicos', '0005_alter_archivomedico_archivo'),
        ('catalogos', '0008_backfill_pueblo_de_luis'),
        ('historias_clinicas', '0006_add_performance_indexes'),
        ('medicos', '0006_medico_nombre_apellido_optional_user'),
        ('pacientes', '0010_paciente_creado_modificado_por'),
        ('solicitudes', '0002_solicitud_lims_paneles_solicitud_lims_tipos_examen'),
        ('turnos', '0007_registroprocedimiento_estudio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEstudioComplementario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('modalidad', models.CharField(choices=[('IMAGEN_RX', 'Imagen — Rayos X'), ('IMAGEN_TC', 'Imagen — Tomografía'), ('IMAGEN_RM', 'Imagen — Resonancia'), ('IMAGEN_US', 'Imagen — Ultrasonido'), ('PDF_INFORME_EXTERNO', 'PDF / informe externo'), ('OTRO', 'Otro')], max_length=40)),
                ('requiere_informe', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de estudio complementario',
                'verbose_name_plural': 'Tipos de estudio complementario',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstudioComplementario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modalidad', models.CharField(choices=[('IMAGEN_RX', 'Imagen — Rayos X'), ('IMAGEN_TC', 'Imagen — Tomografía'), ('IMAGEN_RM', 'Imagen — Resonancia'), ('IMAGEN_US', 'Imagen — Ultrasonido'), ('PDF_INFORME_EXTERNO', 'PDF / informe externo'), ('OTRO', 'Otro')], max_length=40)),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('REALIZADO', 'Realizado'), ('INFORMADO', 'Informado'), ('VALIDADO', 'Validado'), ('ENTREGADO', 'Entregado'), ('ANULADO', 'Anulado')], db_index=True, default='SOLICITADO', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(blank=True, null=True)),
                ('fecha_realizacion', models.DateTimeField(blank=True, null=True)),
                ('centro_realizador', models.CharField(blank=True, max_length=255)),
                ('origen', models.CharField(choices=[('INTERNO', 'Interno'), ('EXTERNO', 'Externo'), ('IMPORTADO_HISTORICO', 'Importado histórico')], default='INTERNO', max_length=30)),
                ('descripcion_clinica', models.TextField(blank=True)),
                ('accession_number', models.CharField(blank=True, max_length=64)),
                ('study_instance_uid', models.CharField(blank=True, db_index=True, max_length=128)),
                ('pacs_metadata', models.JSONField(blank=True, default=dict)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('atencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_complementarios', to='turnos.atencion')),
                ('consulta_hc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_complementarios', to='historias_clinicas.consulta')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_complementarios_creados', to=settings.AUTH_USER_MODEL)),
                ('estudio_diagnostico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_complementarios', to='catalogos.estudiodiagnostico')),
                ('medico_solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_solicitados', to='medicos.medico')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_complementarios_modificados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudios_complementarios', to='pacientes.paciente')),
                ('solicitud_emr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_complementarios', to='solicitudes.solicitud')),
                ('tipo_estudio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios', to='estudios.tipoestudiocomplementario')),
            ],
            options={
                'verbose_name': 'Estudio complementario',
                'verbose_name_plural': 'Estudios complementarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InformeEstudioComplementario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDO', 'Emitido'), ('VALIDADO', 'Validado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20)),
                ('tipo', models.CharField(choices=[('PRELIMINAR', 'Preliminar'), ('FINAL', 'Final')], default='FINAL', max_length=20)),
                ('texto', models.TextField(blank=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='estudios/informes/%Y/%m/')),
                ('es_vigente', models.BooleanField(default=True)),
                ('fecha_informe', models.DateTimeField(blank=True, null=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_rectificacion', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_estudio_creados', to=settings.AUTH_USER_MODEL)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='estudios.estudiocomplementario')),
                ('informado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_estudio_emitidos', to='medicos.medico')),
                ('reemplaza_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_siguientes', to='estudios.informeestudiocomplementario')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_estudio_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Informe de estudio complementario',
                'verbose_name_plural': 'Informes de estudio complementario',
                'ordering': ['-version', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoEstudioComplementario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_rol', models.CharField(choices=[('IMAGEN', 'Imagen'), ('INFORME_ESCANEADO', 'Informe escaneado'), ('DICOM_ZIP', 'DICOM / ZIP'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=500)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('es_principal', models.BooleanField(default=False)),
                ('archivo_medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_estudio', to='archivos_medicos.archivomedico')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_estudio_subidos', to=settings.AUTH_USER_MODEL)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_estudio', to='estudios.estudiocomplementario')),
            ],
            options={
                'verbose_name': 'Archivo de estudio complementario',
                'verbose_name_plural': 'Archivos de estudio complementario',
                'ordering': ['orden', 'id'],
                'constraints': [models.UniqueConstraint(fields=('estudio', 'archivo_medico'), name='uniq_archivo_medico_por_estudio')],
            },
        ),
    ]
