# Generated by Django 5.2.4 on 2025-08-06 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medicos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CentroAtencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre del Centro"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("HOSPITAL", "Hospital"),
                            ("CLINICA", "Clínica"),
                            ("CONSULTORIO", "Consultorio"),
                            ("CENTRO_SALUD", "Centro de Salud"),
                            ("LABORATORIO", "Laboratorio"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Centro",
                    ),
                ),
                ("direccion", models.TextField(verbose_name="Dirección")),
                ("telefono", models.CharField(max_length=20, verbose_name="Teléfono")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Centro de Atención",
                "verbose_name_plural": "Centros de Atención",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="DiagnosticoCIE10",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Código CIE-10"
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "categoria",
                    models.CharField(max_length=100, verbose_name="Categoría"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Diagnóstico CIE-10",
                "verbose_name_plural": "Diagnósticos CIE-10",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Medicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Medicamento"
                    ),
                ),
                (
                    "principio_activo",
                    models.CharField(max_length=200, verbose_name="Principio Activo"),
                ),
                (
                    "presentacion",
                    models.CharField(max_length=100, verbose_name="Presentación"),
                ),
                (
                    "concentracion",
                    models.CharField(max_length=50, verbose_name="Concentración"),
                ),
                (
                    "via_administracion",
                    models.CharField(
                        max_length=50, verbose_name="Vía de Administración"
                    ),
                ),
                (
                    "codigo_atc",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Código ATC"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Medicamento",
                "verbose_name_plural": "Medicamentos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Procedimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Procedimiento"
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "duracion_estimada",
                    models.IntegerField(
                        help_text="Duración en minutos",
                        verbose_name="Duración Estimada",
                    ),
                ),
                (
                    "requiere_anestesia",
                    models.BooleanField(
                        default=False, verbose_name="Requiere Anestesia"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "especialidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicos.especialidad",
                        verbose_name="Especialidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedimiento",
                "verbose_name_plural": "Procedimientos",
                "ordering": ["nombre"],
            },
        ),
    ]
