# Generated by Django 5.2.4 on 2025-08-13 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CentroFisico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        choices=[
                            ("CEHTA", "CEHTA - Centro de Atención Ambulatoria"),
                            ("ICPL", "ICPL - Instituto Cardiológico con Internación"),
                        ],
                        max_length=10,
                        unique=True,
                        verbose_name="Código del Centro",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre del Centro"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "direccion",
                    models.TextField(blank=True, null=True, verbose_name="Dirección"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(default=True, verbose_name="Centro Activo"),
                ),
            ],
            options={
                "verbose_name": "Centro Físico",
                "verbose_name_plural": "Centros Físicos",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="AreaInternacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        choices=[
                            ("UCO", "UCO - Unidad de Cuidados Intensivos"),
                            ("UCE", "UCE - Unidad de Cuidados Especiales"),
                            ("PISO_GENERAL", "Piso General"),
                            ("CIRUGIA", "Área de Cirugía"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Código del Área",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre del Área"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "capacidad_camas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Capacidad de Camas"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(default=True, verbose_name="Área Activa"),
                ),
                (
                    "centro_fisico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas_internacion",
                        to="catalogos.centrofisico",
                        verbose_name="Centro Físico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Área de Internación",
                "verbose_name_plural": "Áreas de Internación",
                "ordering": ["centro_fisico", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="TipoAtencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        choices=[
                            ("AMBULATORIA", "Atención Ambulatoria"),
                            ("GUARDIA_CARDIOLOGICA", "Guardia Cardiológica"),
                            ("INTERNACION_UCO", "Internación UCO (Terapia Intensiva)"),
                            (
                                "INTERNACION_UCE",
                                "Internación UCE (Observación/Intermedia)",
                            ),
                            ("CIRUGIA_AMBULATORIA", "Cirugía Ambulatoria"),
                            ("CIRUGIA_COMPLEJA", "Cirugía Compleja con Internación"),
                        ],
                        max_length=30,
                        unique=True,
                        verbose_name="Código del Tipo",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre del Tipo"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "requiere_internacion",
                    models.BooleanField(
                        default=False, verbose_name="Requiere Internación"
                    ),
                ),
                (
                    "es_urgencia",
                    models.BooleanField(
                        default=False, verbose_name="Es Urgencia/Emergencia"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(default=True, verbose_name="Tipo Activo"),
                ),
                (
                    "centro_fisico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tipos_atencion",
                        to="catalogos.centrofisico",
                        verbose_name="Centro Físico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Atención",
                "verbose_name_plural": "Tipos de Atención",
                "ordering": ["centro_fisico", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="CamaInternacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(max_length=10, verbose_name="Número de Cama"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("DISPONIBLE", "Disponible"),
                            ("OCUPADA", "Ocupada"),
                            ("MANTENIMIENTO", "En Mantenimiento"),
                            ("RESERVADA", "Reservada"),
                        ],
                        default="DISPONIBLE",
                        max_length=20,
                        verbose_name="Estado de la Cama",
                    ),
                ),
                (
                    "tipo_cama",
                    models.CharField(
                        choices=[
                            ("ESTANDAR", "Cama Estándar"),
                            ("UCI", "Cama UCI"),
                            ("UCE", "Cama UCE"),
                            ("POST_QUIRURGICA", "Cama Post-Quirúrgica"),
                        ],
                        default="ESTANDAR",
                        max_length=50,
                        verbose_name="Tipo de Cama",
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(default=True, verbose_name="Cama Activa"),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="camas",
                        to="catalogos.areainternacion",
                        verbose_name="Área",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cama de Internación",
                "verbose_name_plural": "Camas de Internación",
                "ordering": ["area", "numero"],
                "unique_together": {("area", "numero")},
            },
        ),
    ]
