# Generated by Django 5.2.4 on 2025-08-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0002_centrofisico_areainternacion_tipoatencion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camainternacion",
            name="numero",
            field=models.CharField(max_length=20, verbose_name="Número de Cama"),
        ),
    ]
