# Generated by Django 5.2.5 on 2025-08-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0003_alter_camainternacion_numero"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosticocie10",
            name="capitulo",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Capítulo"
            ),
        ),
        migrations.AddField(
            model_name="diagnosticocie10",
            name="enfermedad",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Enfermedad"
            ),
        ),
        migrations.AddField(
            model_name="diagnosticocie10",
            name="tipo_enfermedad",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Tipo de Enfermedad"
            ),
        ),
    ]
