# Generated by Django 5.2.4 on 2025-10-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0004_diagnosticocie10_capitulo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="centrofisico",
            name="codigo",
            field=models.CharField(
                choices=[
                    ("CEHTA", "CEHTA - Centro de Atención Ambulatoria"),
                    (
                        "PUEBLO_DE_LUIS",
                        "PUEBLO DE LUIS - Instituto Cardiológico con Internación",
                    ),
                ],
                max_length=20,
                unique=True,
                verbose_name="Código del Centro",
            ),
        ),
    ]
