# Generated by Django 5.2.4 on 2025-11-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0005_update_centers_to_pueblo_de_luis"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstudioDiagnostico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nombre del Estudio"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Estudio Diagnóstico",
                "verbose_name_plural": "Estudios Diagnóstico",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ProcedimientoCatalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Nombre del Procedimiento",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Procedimiento (Catálogo)",
                "verbose_name_plural": "Procedimientos (Catálogo)",
                "ordering": ["nombre"],
            },
        ),
    ]
