# Generated by Django 5.2.4 on 2026-03-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0006_estudiodiagnostico_procedimientocatalogo"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="diagnosticocie10",
            index=models.Index(fields=["descripcion"], name="cie10_descripcion_idx"),
        ),
    ]
