# Generated by Django 5.2.1 on 2025-05-29 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('turnos', '0002_alter_turno_fecha_hora_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pacientes.paciente', verbose_name='Paciente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Historia Clínica',
                'verbose_name_plural': 'Historias Clínicas',
                'ordering': ['paciente__apellido', 'paciente__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Síntoma')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Síntoma',
                'verbose_name_plural': 'Síntomas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_consulta', models.DateTimeField(verbose_name='Fecha y Hora de la Consulta')),
                ('motivo_consulta_detalle', models.TextField(verbose_name='Motivo de Consulta (Detalle)')),
                ('anamnesis', models.TextField(blank=True, null=True, verbose_name='Anamnesis')),
                ('examen_fisico', models.TextField(blank=True, null=True, verbose_name='Examen Físico')),
                ('diagnostico_presuntivo', models.TextField(blank=True, null=True, verbose_name='Diagnóstico Presuntivo (Texto Libre)')),
                ('plan_manejo', models.TextField(blank=True, null=True, verbose_name='Plan de Manejo / Conducta')),
                ('notas_medicas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales del Médico')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='medicos.medico', verbose_name='Médico Responsable')),
                ('turno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turnos.turno', verbose_name='Turno Asociado')),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='historias_clinicas.historiaclinica', verbose_name='Historia Clínica')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-fecha_hora_consulta'],
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_diagnostico', models.CharField(max_length=255, verbose_name='Diagnóstico Principal')),
                ('codigo_cie', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código CIE-10/CIE-11')),
                ('descripcion_diagnostico', models.TextField(blank=True, null=True, verbose_name='Descripción del Diagnóstico')),
                ('fecha_diagnostico', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Diagnóstico')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='historias_clinicas.consulta', verbose_name='Consulta')),
                ('sintomas_asociados', models.ManyToManyField(blank=True, to='historias_clinicas.sintoma', verbose_name='Síntomas Asociados')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
                'ordering': ['-fecha_diagnostico', 'nombre_diagnostico'],
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tratamiento', models.CharField(choices=[('MEDICAMENTOSO', 'Medicamentoso'), ('PROCEDIMIENTO', 'Procedimiento'), ('TERAPIA', 'Terapia'), ('REPOSO', 'Reposo'), ('OTROS', 'Otros')], max_length=50, verbose_name='Tipo de Tratamiento')),
                ('descripcion_tratamiento', models.TextField(verbose_name='Descripción del Tratamiento')),
                ('dosis_frecuencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dosis / Frecuencia')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin Estimada')),
                ('instrucciones_adicionales', models.TextField(blank=True, null=True, verbose_name='Instrucciones Adicionales')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='historias_clinicas.consulta', verbose_name='Consulta')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'ordering': ['fecha_registro', 'tipo_tratamiento'],
            },
        ),
    ]
