# Generated by Django 5.2.4 on 2025-08-06 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0001_initial"),
        ("historias_clinicas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diagnostico",
            name="codigo_cie",
        ),
        migrations.AddField(
            model_name="diagnostico",
            name="diagnostico_cie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalogos.diagnosticocie10",
                verbose_name="Diagnóstico CIE-10",
            ),
        ),
        migrations.CreateModel(
            name="Prescripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dosis", models.CharField(max_length=100, verbose_name="Dosis")),
                (
                    "frecuencia",
                    models.CharField(max_length=100, verbose_name="Frecuencia"),
                ),
                (
                    "duracion",
                    models.CharField(
                        max_length=100, verbose_name="Duración del Tratamiento"
                    ),
                ),
                (
                    "instrucciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Instrucciones Especiales"
                    ),
                ),
                (
                    "fecha_prescripcion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Prescripción"
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True, verbose_name="Prescripción Activa"
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Fin"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescripciones",
                        to="historias_clinicas.consulta",
                        verbose_name="Consulta",
                    ),
                ),
                (
                    "medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogos.medicamento",
                        verbose_name="Medicamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescripción",
                "verbose_name_plural": "Prescripciones",
                "ordering": ["-fecha_prescripcion"],
            },
        ),
    ]
