# Generated by Django 5.2.5 on 2025-08-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("historias_clinicas", "0002_remove_diagnostico_codigo_cie_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historiaclinica",
            options={
                "ordering": ["paciente__user__last_name", "paciente__user__first_name"],
                "verbose_name": "Historia Clínica",
                "verbose_name_plural": "Historias Clínicas",
            },
        ),
    ]
