# Generated by Django 5.2.4 on 2025-08-13 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0002_centrofisico_areainternacion_tipoatencion_and_more"),
        ("historias_clinicas", "0003_alter_historiaclinica_options"),
        ("medicos", "0004_auto_20250809_0114"),
        ("pacientes", "0004_alter_paciente_options_remove_paciente_alergias_and_more"),
        ("turnos", "0004_turno_centro_fisico_turno_tipo_atencion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Internacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_ingreso",
                    models.DateTimeField(verbose_name="Fecha y Hora de Ingreso"),
                ),
                (
                    "fecha_alta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha y Hora de Alta"
                    ),
                ),
                (
                    "fecha_estimada_alta",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Estimada de Alta"
                    ),
                ),
                ("motivo_ingreso", models.TextField(verbose_name="Motivo de Ingreso")),
                (
                    "diagnostico_ingreso",
                    models.TextField(
                        blank=True, null=True, verbose_name="Diagnóstico de Ingreso"
                    ),
                ),
                (
                    "plan_tratamiento",
                    models.TextField(
                        blank=True, null=True, verbose_name="Plan de Tratamiento"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVA", "Activa"),
                            ("ALTA_MEDICA", "Alta Médica"),
                            ("ALTA_VOLUNTARIA", "Alta Voluntaria"),
                            ("TRANSFERENCIA", "Transferencia a otro centro"),
                            ("FALLECIMIENTO", "Fallecimiento"),
                        ],
                        default="ACTIVA",
                        max_length=20,
                        verbose_name="Estado de la Internación",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "numero_internacion",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Número de Internación"
                    ),
                ),
                (
                    "es_urgencia",
                    models.BooleanField(
                        default=False, verbose_name="Es Urgencia/Emergencia"
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "ultima_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "cama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internaciones",
                        to="catalogos.camainternacion",
                        verbose_name="Cama Asignada",
                    ),
                ),
                (
                    "medico_responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="internaciones_responsable",
                        to="medicos.medico",
                        verbose_name="Médico Responsable",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internaciones",
                        to="pacientes.paciente",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "turno_origen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="internaciones",
                        to="turnos.turno",
                        verbose_name="Turno de Origen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Internación",
                "verbose_name_plural": "Internaciones",
                "ordering": ["-fecha_ingreso"],
            },
        ),
    ]
