# Generated by Django 5.2.8 on 2025-11-26 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_estudiodiagnostico_procedimientocatalogo'),
        ('historias_clinicas', '0004_internacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescripcion',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.medicamento', verbose_name='Medicamento'),
        ),
    ]
