# Generated by Django 5.2.4 on 2026-03-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("historias_clinicas", "0005_alter_prescripcion_medicamento"),
        ("medicos", "0006_medico_nombre_apellido_optional_user"),
        ("turnos", "0007_registroprocedimiento_estudio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historiaclinica",
            options={
                "ordering": ["paciente__apellido", "paciente__nombre"],
                "verbose_name": "Historia Clínica",
                "verbose_name_plural": "Historias Clínicas",
            },
        ),
        migrations.AddIndex(
            model_name="consulta",
            index=models.Index(
                fields=["-fecha_hora_consulta"], name="hist_consulta_fecha_idx"
            ),
        ),
    ]
