# Generated by Django 5.2.4 on 2025-08-07 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("direccion", models.TextField(blank=True, null=True)),
                ("ciudad", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "codigo_postal",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "grupo_sanguineo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "alergias",
                    models.TextField(
                        blank=True, help_text="Lista de alergias conocidas", null=True
                    ),
                ),
                (
                    "medicamentos_actuales",
                    models.TextField(
                        blank=True,
                        help_text="Medicamentos que toma actualmente",
                        null=True,
                    ),
                ),
                (
                    "contacto_emergencia_nombre",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contacto_emergencia_telefono",
                    models.CharField(blank=True, max_length=17, null=True),
                ),
                (
                    "contacto_emergencia_relacion",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuario",
                "db_table": "pacientes_userprofile",
            },
        ),
    ]
