# Generated by Django 5.2.5 on 2025-08-09 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0003_auto_20250808_1311"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paciente",
            options={
                "ordering": ["user__last_name", "user__first_name"],
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
            },
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="alergias",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="apellido",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="direccion",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="email",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="fecha_nacimiento",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="medicacion_actual",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="nombre",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="sexo",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="telefono",
        ),
        migrations.AddField(
            model_name="paciente",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paciente",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario del Sistema",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
