# Generated by Django 5.2.4 on 2025-08-14 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0004_alter_paciente_options_remove_paciente_alergias_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="apellido",
            field=models.CharField(default="", max_length=100, verbose_name="Apellido"),
        ),
        migrations.AddField(
            model_name="paciente",
            name="direccion",
            field=models.TextField(blank=True, null=True, verbose_name="Dirección"),
        ),
        migrations.AddField(
            model_name="paciente",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="fecha_nacimiento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Nacimiento"
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="nombre",
            field=models.CharField(default="", max_length=100, verbose_name="Nombre"),
        ),
        migrations.AddField(
            model_name="paciente",
            name="numero_afiliado",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Número de Afiliado"
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="obra_social",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Obra Social"
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="observaciones",
            field=models.TextField(blank=True, null=True, verbose_name="Observaciones"),
        ),
        migrations.AddField(
            model_name="paciente",
            name="sexo",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculino"), ("F", "Femenino")],
                max_length=1,
                null=True,
                verbose_name="Sexo",
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="telefono",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Teléfono"
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paciente",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario del Sistema",
            ),
        ),
    ]
