# Generated by Django 5.2.4 on 2026-05-18 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario operador que dio de alta la ficha (no la cuenta portal del paciente).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='modificado_por',
            field=models.ForeignKey(blank=True, help_text='Último usuario operador que modificó la ficha.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
    ]
