# Generated by Django 5.2.4 on 2025-08-20 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medicos", "0004_auto_20250809_0114"),
        (
            "pacientes",
            "0005_paciente_apellido_paciente_direccion_paciente_email_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitudExamenLims",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lims_id",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="ID de la Solicitud en LIMS",
                    ),
                ),
                (
                    "numero_solicitud",
                    models.CharField(
                        max_length=20, verbose_name="Número de Solicitud LIMS"
                    ),
                ),
                (
                    "fecha_solicitud",
                    models.DateTimeField(verbose_name="Fecha de Solicitud"),
                ),
                ("estado", models.CharField(max_length=20, verbose_name="Estado LIMS")),
                (
                    "medico_solicitante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="medicos.medico",
                        verbose_name="Médico Solicitante",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes_lims",
                        to="pacientes.paciente",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Examen (LIMS)",
                "verbose_name_plural": "Solicitudes de Exámenes (LIMS)",
                "ordering": ["-fecha_solicitud"],
            },
        ),
        migrations.CreateModel(
            name="ResultadoExamenLims",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lims_id",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="ID del Resultado en LIMS",
                    ),
                ),
                (
                    "tipo_examen",
                    models.CharField(max_length=200, verbose_name="Tipo de Examen"),
                ),
                (
                    "valor_numerico",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor Numérico",
                    ),
                ),
                (
                    "valor_texto",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Valor Texto"
                    ),
                ),
                (
                    "es_normal",
                    models.BooleanField(default=True, verbose_name="¿Es Normal?"),
                ),
                (
                    "solicitud_lims",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados_lims",
                        to="integracion_lims.solicitudexamenlims",
                        verbose_name="Solicitud LIMS",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado de Examen (LIMS)",
                "verbose_name_plural": "Resultados de Exámenes (LIMS)",
            },
        ),
    ]
