# Generated by Django 5.2.4 on 2025-11-12 03:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("turnos", "0005_atencion_recurso_alter_turno_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("INFORME", "Informe"),
                            ("IMAGEN", "Imagen"),
                            ("CONSENTIMIENTO", "Consentimiento"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("archivo", models.FileField(upload_to="emr/documentos/")),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "atencion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="turnos.atencion",
                    ),
                ),
                (
                    "usuario_cargador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_emr_cargados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Clínico",
                "verbose_name_plural": "Documentos Clínicos",
                "ordering": ["-fecha_subida"],
            },
        ),
        migrations.CreateModel(
            name="SignosVitales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rol_registrador",
                    models.CharField(
                        choices=[
                            ("MEDICO", "Médico"),
                            ("ENFERMERIA", "Enfermería"),
                            ("ADMINISTRATIVO", "Administrativo"),
                            ("OTRO", "Otro"),
                        ],
                        default="MEDICO",
                        max_length=50,
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "tension_arterial",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "frecuencia_cardiaca",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "frecuencia_respiratoria",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "temperatura",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "saturacion_oxigeno",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "indice_masa_corporal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "peso",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "talla",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "atencion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signos_vitales",
                        to="turnos.atencion",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signos_vitales_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Signos Vitales",
                "verbose_name_plural": "Signos Vitales",
                "ordering": ["-fecha_registro", "-created_at"],
            },
        ),
    ]
