# Generated by Django 5.2.4 on 2026-01-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("INFORME", "Informe"),
                    ("ESTUDIO", "Estudio"),
                    ("ANALISIS", "Análisis"),
                    ("DIAGNOSTICO", "Diagnóstico"),
                    ("IMAGEN", "Imagen"),
                    ("CONSENTIMIENTO", "Consentimiento"),
                    ("OTRO", "Otro"),
                ],
                max_length=20,
            ),
        ),
    ]
