# Generated by Django 5.2.5 on 2025-08-14 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("historias_clinicas", "0004_internacion"),
        (
            "pacientes",
            "0005_paciente_apellido_paciente_direccion_paciente_email_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivoMedico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título del Archivo"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "tipo_archivo",
                    models.CharField(
                        choices=[
                            ("radiografia", "Radiografía"),
                            ("ecografia", "Ecografía"),
                            ("analisis_sangre", "Análisis de Sangre"),
                            ("analisis_orina", "Análisis de Orina"),
                            ("electrocardiograma", "Electrocardiograma"),
                            ("resonancia", "Resonancia Magnética"),
                            ("tomografia", "Tomografía"),
                            ("endoscopia", "Endoscopia"),
                            ("biopsia", "Biopsia"),
                            ("otro", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Archivo",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to="archivos_medicos/%Y/%m/%d/", verbose_name="Archivo"
                    ),
                ),
                (
                    "fecha_subida",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Subida"
                    ),
                ),
                (
                    "fecha_estudio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha del Estudio"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "es_urgente",
                    models.BooleanField(default=False, verbose_name="Es Urgente"),
                ),
                (
                    "consulta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archivos",
                        to="historias_clinicas.consulta",
                        verbose_name="Consulta Relacionada",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archivos_medicos",
                        to="pacientes.paciente",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "subido_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Subido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo Médico",
                "verbose_name_plural": "Archivos Médicos",
                "ordering": ["-fecha_subida"],
            },
        ),
    ]
