# Generated by Django 5.2.5 on 2025-08-15 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archivos_medicos", "0001_initial"),
        ("historias_clinicas", "0004_internacion"),
        (
            "pacientes",
            "0005_paciente_apellido_paciente_direccion_paciente_email_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="archivomedico",
            name="observaciones",
        ),
        migrations.AlterField(
            model_name="archivomedico",
            name="consulta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archivos",
                to="historias_clinicas.consulta",
                verbose_name="Consulta Asociada",
            ),
        ),
        migrations.AlterField(
            model_name="archivomedico",
            name="paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archivos",
                to="pacientes.paciente",
                verbose_name="Paciente",
            ),
        ),
        migrations.AlterField(
            model_name="archivomedico",
            name="tipo_archivo",
            field=models.CharField(
                choices=[
                    ("DICOM", "DICOM (.dcm)"),
                    ("NIFTI", "NIFTI (.nii, .nii.gz)"),
                    ("RAYOS_X", "Rayos X (imagen estandarizada)"),
                    ("TOMOGRAFIA", "Tomografía"),
                    ("RESONANCIA", "Resonancia Magnética"),
                    ("ULTRASONIDO", "Ultrasonido"),
                    ("FOTO_CLINICA", "Foto Clínica (.jpg, .png)"),
                    ("PATOLOGIA", "Patología (.tif, .png)"),
                    ("PDF", "Documento PDF"),
                    ("OTRO", "Otro"),
                ],
                max_length=50,
                verbose_name="Tipo de Archivo",
            ),
        ),
    ]
