# Generated by Django 5.2.5 on 2025-08-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archivos_medicos", "0003_alter_archivomedico_subido_por"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivomedico",
            name="archivo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="archivos_medicos/%Y/%m/%d/",
                verbose_name="Archivo",
            ),
        ),
    ]
