# Generated by Django 5.2.8 on 2025-11-26 03:19

import archivos_medicos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos_medicos', '0004_alter_archivomedico_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivomedico',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos_medicos/%Y/%m/%d/', validators=[archivos_medicos.validators.validar_tamanio_archivo, archivos_medicos.validators.validar_extension_archivo], verbose_name='Archivo'),
        ),
    ]
