# Generated by Django 5.2.1 on 2025-05-29 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField(verbose_name='Fecha y Hora de Inicio')),
                ('fecha_hora_fin', models.DateTimeField(verbose_name='Fecha y Hora de Fin')),
                ('motivo_consulta', models.TextField(blank=True, null=True, verbose_name='Motivo de Consulta')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado'), ('REAGENDADO', 'Reagendado')], default='PENDIENTE', max_length=20, verbose_name='Estado del Turno')),
                ('notas_administrativas', models.TextField(blank=True, null=True, verbose_name='Notas Administrativas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('especialidad_turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicos.especialidad', verbose_name='Especialidad del Turno')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='medicos.medico', verbose_name='Médico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['fecha_hora_inicio'],
            },
        ),
    ]
