# Generated by Django 5.2.1 on 2025-05-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha_hora_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Fin'),
        ),
    ]
