# Generated by Django 5.2.4 on 2025-08-06 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0001_initial"),
        ("turnos", "0002_alter_turno_fecha_hora_fin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="turno",
            old_name="especialidad_turno",
            new_name="especialidad",
        ),
        migrations.AddField(
            model_name="turno",
            name="fecha_hora",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha y Hora del Turno"
            ),
        ),
        migrations.AlterField(
            model_name="turno",
            name="estado",
            field=models.CharField(
                choices=[
                    ("DISPONIBLE", "Disponible"),
                    ("RESERVADO", "Reservado"),
                    ("CONFIRMADO", "Confirmado"),
                    ("REALIZADO", "Realizado"),
                    ("CANCELADO", "Cancelado"),
                    ("REAGENDADO", "Reagendado"),
                ],
                default="DISPONIBLE",
                max_length=20,
                verbose_name="Estado del Turno",
            ),
        ),
        migrations.AlterField(
            model_name="turno",
            name="paciente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turnos",
                to="pacientes.paciente",
                verbose_name="Paciente",
            ),
        ),
    ]
