# Generated by Django 5.2.4 on 2025-08-13 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0002_centrofisico_areainternacion_tipoatencion_and_more"),
        ("turnos", "0003_rename_especialidad_turno_turno_especialidad_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="turno",
            name="centro_fisico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="turnos",
                to="catalogos.centrofisico",
                verbose_name="Centro Físico",
            ),
        ),
        migrations.AddField(
            model_name="turno",
            name="tipo_atencion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="turnos",
                to="catalogos.tipoatencion",
                verbose_name="Tipo de Atención",
            ),
        ),
    ]
