# Generated by Django 5.2.4 on 2025-11-12 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0006_estudiodiagnostico_procedimientocatalogo"),
        ("emr", "0001_initial"),
        ("medicos", "0006_medico_nombre_apellido_optional_user"),
        ("turnos", "0005_atencion_recurso_alter_turno_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="atencion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="atencion",
            name="estado_clinico",
            field=models.CharField(
                choices=[
                    ("ABIERTA", "Abierta"),
                    ("FINALIZADA", "Finalizada"),
                    ("EN_REVISION", "En revisión"),
                ],
                default="ABIERTA",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="atencion",
            name="observaciones_generales",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="atencion",
            name="tipo_intervencion",
            field=models.CharField(
                choices=[
                    ("CONSULTA", "Consulta"),
                    ("ESTUDIO", "Estudio"),
                    ("PROCEDIMIENTO", "Procedimiento"),
                    ("CIRUGIA", "Cirugía"),
                ],
                default="CONSULTA",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="atencion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="consultaambulatoria",
            name="alergias",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultaambulatoria",
            name="antecedentes_relevantes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultaambulatoria",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="consultaambulatoria",
            name="diagnostico_definitivo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultaambulatoria",
            name="medicacion_actual",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultaambulatoria",
            name="observaciones_medicas",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultaambulatoria",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="recurso",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="recurso",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="registroprocedimiento",
            name="adjunto_resultado",
            field=models.FileField(
                blank=True, null=True, upload_to="emr/procedimientos/"
            ),
        ),
        migrations.AddField(
            model_name="registroprocedimiento",
            name="complicaciones",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registroprocedimiento",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="registroprocedimiento",
            name="procedimiento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registros_procedimiento",
                to="catalogos.procedimientocatalogo",
            ),
        ),
        migrations.AddField(
            model_name="registroprocedimiento",
            name="profesional_asistente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="procedimientos_asistente",
                to="medicos.medico",
            ),
        ),
        migrations.AddField(
            model_name="registroprocedimiento",
            name="tipo_procedimiento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DIAGNOSTICO", "Diagnóstico"),
                    ("TERAPEUTICO", "Terapéutico"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="registroprocedimiento",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="registroquirurgico",
            name="complicaciones",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registroquirurgico",
            name="consentimiento_informado",
            field=models.FileField(
                blank=True, null=True, upload_to="emr/consentimientos/"
            ),
        ),
        migrations.AddField(
            model_name="registroquirurgico",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="registroquirurgico",
            name="diagnostico_postoperatorio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registroquirurgico",
            name="documentos_adjuntos",
            field=models.ManyToManyField(
                blank=True, related_name="registros_quirurgicos", to="emr.documento"
            ),
        ),
        migrations.AddField(
            model_name="registroquirurgico",
            name="equipo_quirurgico",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="registroquirurgico",
            name="hallazgos_operatorios",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registroquirurgico",
            name="procedimiento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registros_quirurgicos",
                to="catalogos.procedimientocatalogo",
            ),
        ),
        migrations.AddField(
            model_name="registroquirurgico",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="turno",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="turno",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
