# Generated by Django 5.2.4 on 2025-11-17 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0006_estudiodiagnostico_procedimientocatalogo"),
        ("turnos", "0006_atencion_created_at_atencion_estado_clinico_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroprocedimiento",
            name="estudio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registros_procedimiento",
                to="catalogos.estudiodiagnostico",
            ),
        ),
    ]
