# Generated by Django 6.0.6 on 2026-09-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0009_tipo_atencion_guardia'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='asistencia_confirmada_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
