# Generated by Django 5.2.4 on 2025-08-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = []
