# Generated by Django 5.2.5 on 2025-08-09 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_auto_20250808_1311"),
    ]

    operations = [
        migrations.CreateModel(
            name="Secretaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legajo",
                    models.CharField(max_length=20, unique=True, verbose_name="Legajo"),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Sector"
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "ultima_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secretaria",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Secretaria",
                "verbose_name_plural": "Secretarias",
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
    ]
