# Generated by Django 5.2.4 on 2025-11-10 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_secretaria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telefono",
            field=models.CharField(
                blank=True,
                help_text="Número de teléfono",
                max_length=25,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El número de teléfono debe estar en formato: '+999999999'. Hasta 15 dígitos permitidos.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
