# Generated by Django 5.2.4 on 2025-11-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_alter_user_telefono"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="rol",
            field=models.CharField(
                choices=[
                    ("paciente", "Paciente"),
                    ("medico", "Médico"),
                    ("secretaria", "Secretaria"),
                    ("enfermeria", "Enfermería"),
                    ("admin", "Administrador"),
                ],
                default="paciente",
                help_text="Rol del usuario en el sistema",
                max_length=20,
            ),
        ),
    ]
