# Generated by Django 5.2.8 on 2025-11-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('paciente', 'Paciente'), ('medico', 'Médico'), ('secretaria', 'Secretaria'), ('enfermeria', 'Enfermería'), ('admin', 'Administrador')], default='paciente', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
