# Generated by Django 6.0.6 on 2026-06-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_user_rol_laboratorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('paciente', 'Paciente'), ('medico', 'Médico'), ('secretaria', 'Secretaria'), ('enfermeria', 'Enfermería'), ('laboratorio', 'Laboratorio'), ('kinesiologo', 'Kinesiólogo'), ('radiologo', 'Radiólogo'), ('ecografista', 'Ecografista'), ('fonoaudiologo', 'Fonoaudiólogo'), ('admin', 'Administrador')], default='paciente', max_length=20),
        ),
    ]
