# Generated by Django 5.2.4 on 2025-11-18 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medicos", "0006_medico_nombre_apellido_optional_user"),
        ("pacientes", "0008_alter_paciente_options_paciente_apellido_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cama",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, verbose_name="Nombre de la Cama"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("DISPONIBLE", "Disponible"),
                            ("OCUPADA", "Ocupada"),
                            ("LIMPIEZA", "En Limpieza"),
                            ("MANTENIMIENTO", "En Mantenimiento"),
                        ],
                        default="DISPONIBLE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cama",
                "verbose_name_plural": "Camas",
                "ordering": ["sector", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nombre del Sector"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sector",
                "verbose_name_plural": "Sectores",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Internacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_ingreso",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Ingreso"
                    ),
                ),
                (
                    "fecha_alta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Alta"
                    ),
                ),
                (
                    "diagnostico_ingreso",
                    models.TextField(verbose_name="Diagnóstico de Ingreso"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "cama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internaciones",
                        to="internacion.cama",
                        verbose_name="Cama",
                    ),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="internaciones_camas",
                        to="medicos.medico",
                        verbose_name="Médico",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internaciones_camas",
                        to="pacientes.paciente",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Internación",
                "verbose_name_plural": "Internaciones",
                "ordering": ["-fecha_ingreso"],
            },
        ),
        migrations.AddField(
            model_name="cama",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="camas",
                to="internacion.sector",
                verbose_name="Sector",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cama",
            unique_together={("nombre", "sector")},
        ),
    ]
