# Generated by Django 5.2.4 on 2025-11-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internacion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cama",
            name="aislada",
            field=models.BooleanField(default=False, verbose_name="Cama Aislada"),
        ),
    ]
