# Generated by Django 5.2.4 on 2025-11-19 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0006_estudiodiagnostico_procedimientocatalogo"),
        ("internacion", "0002_cama_aislada"),
    ]

    operations = [
        migrations.AddField(
            model_name="internacion",
            name="diagnostico_cie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="internaciones",
                to="catalogos.diagnosticocie10",
                verbose_name="Diagnóstico CIE-10",
            ),
        ),
        migrations.AlterField(
            model_name="internacion",
            name="diagnostico_ingreso",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Diagnóstico de Ingreso (texto libre)",
            ),
        ),
    ]
