# Generated by Django 4.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internacion', '0005_tipodieta_internacion_tipo_dieta'),
    ]

    operations = [
        migrations.AddField(
            model_name='internacion',
            name='alergias',
            field=models.TextField(blank=True, default='', verbose_name='Alergias'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='anamnesis_ingreso',
            field=models.TextField(blank=True, default='', verbose_name='Anamnesis de ingreso'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='examen_fisico_ingreso',
            field=models.TextField(blank=True, default='', verbose_name='Examen físico de ingreso'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='medicacion_habitual',
            field=models.TextField(blank=True, default='', verbose_name='Medicación habitual'),
        ),
        migrations.CreateModel(
            name='IndicacionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('hidratacion', models.CharField(blank=True, default='', max_length=255)),
                ('oxigenoterapia', models.CharField(blank=True, default='', max_length=255)),
                ('reposo', models.CharField(blank=True, default='', max_length=255)),
                ('controles', models.CharField(blank=True, default='', help_text='TA, FC, glucemia, diuresis, etc.', max_length=255)),
                ('precauciones', models.TextField(blank=True, default='')),
                ('indicaciones', models.TextField(blank=True, default='')),
                ('vigente', models.BooleanField(default=True)),
                ('internacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicaciones_medicas', to='internacion.internacion')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicaciones_internacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Indicación médica',
                'verbose_name_plural': 'Indicaciones médicas',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MedicacionInternacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('medicamento', models.CharField(max_length=200)),
                ('dosis', models.CharField(blank=True, default='', max_length=100)),
                ('via', models.CharField(blank=True, default='', max_length=80)),
                ('frecuencia', models.CharField(blank=True, default='', max_length=100)),
                ('horario', models.CharField(blank=True, default='', max_length=120)),
                ('activa', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('internacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaciones', to='internacion.internacion')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicaciones_internacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medicación de internación',
                'verbose_name_plural': 'Medicaciones de internación',
                'ordering': ['-activa', '-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ControlEnfermeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('turno', models.CharField(choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche')], max_length=10)),
                ('tension_arterial', models.CharField(blank=True, default='', max_length=15)),
                ('frecuencia_cardiaca', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('frecuencia_respiratoria', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('saturacion_oxigeno', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('dolor', models.PositiveSmallIntegerField(blank=True, help_text='EVA 0-10', null=True)),
                ('glucemia', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('internacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_enfermeria', to='internacion.internacion')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_enfermeria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Control de enfermería',
                'verbose_name_plural': 'Controles de enfermería',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BalanceHidrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('turno', models.CharField(choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche')], max_length=10)),
                ('ingresos_vo_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('ingresos_ev_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('diuresis_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('otros_egresos_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('internacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances_hidricos', to='internacion.internacion')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balances_hidricos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Balance hídrico',
                'verbose_name_plural': 'Balances hídricos',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotaEnfermeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('curaciones', models.TextField(blank=True, default='')),
                ('dispositivos', models.TextField(blank=True, default='', help_text='SV, acceso venoso, O2, SNG, etc.')),
                ('internacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_enfermeria', to='internacion.internacion')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_enfermeria_internacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de enfermería',
                'verbose_name_plural': 'Notas de enfermería',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RegistroKinesiologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('frecuencia_respiratoria', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('saturacion_oxigeno', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('oxigenoterapia', models.CharField(blank=True, default='', max_length=120)),
                ('secreciones', models.CharField(blank=True, default='', max_length=255)),
                ('tecnica', models.TextField(blank=True, default='', help_text='Técnica kine aplicada')),
                ('movilizacion', models.CharField(blank=True, default='', max_length=255)),
                ('evolucion', models.TextField(blank=True, default='')),
                ('plan', models.TextField(blank=True, default='')),
                ('internacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_kinesiologia', to='internacion.internacion')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_kinesiologia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de kinesiología',
                'verbose_name_plural': 'Registros de kinesiología',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
