# Generated by Django 4.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internacion', '0006_formularios_hc_papel'),
    ]

    operations = [
        migrations.AddField(
            model_name='internacion',
            name='tiene_alergias',
            field=models.BooleanField(
                blank=True,
                help_text='None = no informado; True = Sí; False = No',
                null=True,
                verbose_name='¿Alergias?',
            ),
        ),
        migrations.AddField(
            model_name='internacion',
            name='plan_estudio_tratamiento',
            field=models.TextField(blank=True, default='', verbose_name='Plan de estudio / tratamiento'),
        ),
        migrations.CreateModel(
            name='MedicacionHabitualInternacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('medicamento', models.CharField(max_length=200)),
                ('dosis_mg_dia', models.CharField(blank=True, default='', max_length=50)),
                ('internacion', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='medicaciones_habituales',
                    to='internacion.internacion',
                )),
                ('registrado_por', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='medicaciones_habituales_internacion',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'verbose_name': 'Medicación habitual de ingreso',
                'verbose_name_plural': 'Medicaciones habituales de ingreso',
                'ordering': ['id'],
            },
        ),
    ]
