# Generated by Django 5.2.5 on 2025-08-20 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medicos", "0004_auto_20250809_0114"),
        (
            "pacientes",
            "0005_paciente_apellido_paciente_direccion_paciente_email_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Solicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_solicitud",
                    models.CharField(
                        choices=[
                            ("EXAMEN_LABORATORIO", "Examen de Laboratorio"),
                            ("ESTUDIO_IMAGEN", "Estudio de Imagen"),
                            ("CONSULTA_ESPECIALISTA", "Consulta con Especialista"),
                            ("PROCEDIMIENTO", "Procedimiento"),
                            ("OTRO", "Otro"),
                        ],
                        default="EXAMEN_LABORATORIO",
                        max_length=50,
                        verbose_name="Tipo de Solicitud",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "fecha_solicitud",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Solicitud"
                    ),
                ),
                (
                    "fecha_limite",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Límite"
                    ),
                ),
                (
                    "fecha_completada",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Completada"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En Proceso"),
                            ("COMPLETADA", "Completada"),
                            ("CANCELADA", "Cancelada"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("BAJA", "Baja"),
                            ("NORMAL", "Normal"),
                            ("ALTA", "Alta"),
                            ("URGENTE", "Urgente"),
                        ],
                        default="NORMAL",
                        max_length=20,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "lims_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="ID de solicitud en LIMS",
                    ),
                ),
                (
                    "sincronizado_lims",
                    models.BooleanField(
                        default=False, verbose_name="Sincronizado con LIMS"
                    ),
                ),
                (
                    "ultima_sincronizacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última Sincronización"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_creadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "medico_solicitante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_realizadas",
                        to="medicos.medico",
                        verbose_name="Médico Solicitante",
                    ),
                ),
                (
                    "medicos_asignados",
                    models.ManyToManyField(
                        blank=True,
                        related_name="solicitudes_asignadas",
                        to="medicos.medico",
                        verbose_name="Médicos Asignados",
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_modificadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modificado por",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes",
                        to="pacientes.paciente",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud",
                "verbose_name_plural": "Solicitudes",
                "ordering": ["-fecha_solicitud"],
                "indexes": [
                    models.Index(
                        fields=["estado", "fecha_solicitud"],
                        name="solicitudes_estado_6fb1de_idx",
                    ),
                    models.Index(
                        fields=["paciente", "estado"],
                        name="solicitudes_pacient_78ebb1_idx",
                    ),
                    models.Index(
                        fields=["medico_solicitante", "estado"],
                        name="solicitudes_medico__50e5e5_idx",
                    ),
                ],
            },
        ),
    ]
