# Generated by Django 5.2.4 on 2025-08-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitudes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitud",
            name="lims_paneles",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Paneles LIMS seleccionados"
            ),
        ),
        migrations.AddField(
            model_name="solicitud",
            name="lims_tipos_examen",
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name="Tipos de examen LIMS seleccionados",
            ),
        ),
    ]
