/** Prácticas CEHTA — alineado a estudios/practicas_cehta.py (slugs). */
export const CEHTA_PRACTICA_OPTIONS: { value: string; label: string }[] = [
  { value: 'CARDIOGRAFIA_POR_IMPEDANCIA', label: 'Cardiografía por impedancia' },
  { value: 'COLOCACION_DE_DISPOSITIVO_INTRAUTERINO', label: 'Colocación de Dispositivo intrauterino' },
  { value: 'COLPOCITOLOGIA', label: 'Colpocitología' },
  { value: 'COLPOSCOPIA', label: 'Colposcopía' },
  { value: 'CONSULTA_ESPECIALISTA_EN_CARDIOLOGIA', label: 'Consulta especialista en cardiología' },
  { value: 'CONSULTA_ESPECIALISTA_EN_CIRUGIA', label: 'Consulta especialista en cirugía' },
  { value: 'CONSULTA_ESPECIALISTA_EN_DIABETOLOGIA', label: 'Consulta especialista en diabetología' },
  { value: 'CONSULTA_ESPECIALISTA_EN_GINECOLOGIA', label: 'Consulta especialista en ginecología' },
  { value: 'CONSULTA_ESPECIALISTA_EN_NEFROLOGIA', label: 'Consulta especialista en nefrología' },
  { value: 'CONSULTA_ESPECIALISTA_EN_NEUMONOLOGIA', label: 'Consulta especialista en neumonología' },
  { value: 'CONSULTA_ESPECIALISTA_EN_NUTRICION', label: 'Consulta especialista en nutrición' },
  { value: 'CONSULTA_ESPECIALISTA_EN_TRAUMATOLOGIA', label: 'Consulta especialista en traumatología' },
  { value: 'CONSULTA_ESPECIALISTA_EN_UROLOGIA', label: 'Consulta especialista en urología' },
  { value: 'CONSULTA_MEDICA', label: 'Consulta médica' },
  { value: 'CONTROL_DE_MARCAPASOS', label: 'Control de marcapasos' },
  { value: 'DOPPLER_ARTERIAL_MIEMBROS_INF', label: 'Doppler arterial miembros inf.' },
  { value: 'DOPPLER_ARTERIAL_MIEMBROS_SUP', label: 'Doppler arterial miembros sup.' },
  { value: 'DOPPLER_ARTERIO_VENOSO_DE_MIEMBROS_INFERIORES', label: 'Doppler arterio-venoso de miembros inferiores' },
  { value: 'DOPPLER_ARTERIO_VENOSO_DE_MIEMBROS_SUPERIORES', label: 'Doppler arterio-venoso de miembros superiores' },
  { value: 'DOPPLER_CARDIACO', label: 'Doppler cardíaco' },
  { value: 'DOPPLER_DE_AORTA_ABDOMINAL', label: 'Doppler de aorta abdominal' },
  { value: 'DOPPLER_DE_RINON', label: 'Doppler de Riñón' },
  { value: 'DOPPLER_DE_TESTICULOS', label: 'Doppler de testículos' },
  { value: 'DOPPLER_DE_TIROIDES', label: 'Doppler de tiroides' },
  { value: 'DOPPLER_DE_VASOS_DE_CUELLO', label: 'Doppler de vasos de cuello' },
  { value: 'DOPPLER_TRANSESOFAGICO', label: 'Doppler transesofágico' },
  { value: 'DOPPLER_TRANSVAGINAL', label: 'Doppler transvaginal' },
  { value: 'DOPPLER_VENOSO_MIEMBROS_INF', label: 'Doppler venoso miembros inf.' },
  { value: 'DOPPLER_VENOSO_MIEMBROS_SUP', label: 'Doppler venoso miembros sup.' },
  { value: 'ECOCARDIOGRAMA_DE_ESTRES', label: 'Ecocardiograma de estrés' },
  { value: 'ECODOPPLER_AORTO_ILIACO', label: 'Ecodoppler aorto ilíaco' },
  { value: 'ECODOPPLER_ARTERIAL_Y_O_VENOSO_DE_OTRAS_REGIONES', label: 'Ecodoppler arterial y/o venoso de otras regiones' },
  { value: 'ECODOPPLER_CIRCULACION_PORTAL', label: 'Ecodoppler circulación portal' },
  { value: 'ECOGRAFIA_COMPLETA_DE_ABDOMEN', label: 'Ecografía completa de abdomen' },
  { value: 'ECOGRAFIA_DE_AORTA_ABDOMINAL', label: 'Ecografía de aorta abdominal' },
  { value: 'ECOGRAFIA_DE_PARTES_BLANDAS', label: 'Ecografía de partes blandas' },
  { value: 'ECOGRAFIA_DE_TESTICULOS', label: 'Ecografía de testículos' },
  { value: 'ECOGRAFIA_DE_TIROIDES', label: 'Ecografía de tiroides' },
  { value: 'ECOGRAFIA_GINECOLOGICA', label: 'Ecografía ginecológica' },
  { value: 'ECOGRAFIA_HEPATICA_VIAS_BILIARES', label: 'Ecografía hepatica / vias biliares' },
  { value: 'ECOGRAFIA_MAMARIA', label: 'Ecografía mamaria' },
  { value: 'ECOGRAFIA_PANCREATICA_O_SUPRARENAL', label: 'Ecografía pancreática o suprarenal' },
  { value: 'ECOGRAFIA_RENAL', label: 'Ecografía Renal' },
  { value: 'ECOGRAFIA_TRANSVAGINAL', label: 'Ecografía transvaginal' },
  { value: 'ECOGRAFIA_VESICAL_PROSTATICA', label: 'Ecografía vesical / prostática' },
  { value: 'ELECTROCARDIOGRAMA', label: 'Electrocardiograma' },
  { value: 'ERGOESPIROMETRIA', label: 'Ergoespirometría' },
  { value: 'ERGOMETRIA_DE_12_DERIVACIONES', label: 'Ergometría de 12 derivaciones' },
  {
    value: 'ESCISION_LOCAL_ELECTROCOAGULACION_BIOPSIA_CUELLO_V',
    label: 'Escisión local, electrocoagulación, Biopsia (cuello, vulva, vagina)',
  },
  { value: 'ESPIROMETRIA', label: 'Espirometría' },
  { value: 'HIMENOTOMIA', label: 'Himenotomía' },
  { value: 'HOLTER_3_CANALES', label: 'Holter 3 canales' },
  { value: 'MAPA', label: 'MAPA' },
  { value: 'PRESUROMETRIA_SEGMENTARIA', label: 'Presurometria Segmentaria' },
  { value: 'PUNCION_BIOPSIA_MAMARIA_CON_AGUJA_FINA', label: 'Punción biopsia mamaria con aguja fina' },
  { value: 'REHABILITACION_CARDIOPULMONAR', label: 'Rehabilitación Cardiopulmonar' },
  { value: 'TEST_DE_MARCHA_O_CAMINATA', label: 'Test de marcha o caminata' },
];

export const LEGACY_PRACTICA_OPTIONS: { value: string; label: string }[] = [
  { value: 'IMAGEN_RX', label: 'Rayos X (histórico)' },
  { value: 'IMAGEN_TC', label: 'Tomografía (histórico)' },
  { value: 'IMAGEN_RM', label: 'Resonancia (histórico)' },
  { value: 'IMAGEN_US', label: 'Ultrasonido (histórico)' },
  { value: 'PDF_INFORME_EXTERNO', label: 'PDF / informe externo' },
  { value: 'OTRO', label: 'Otro' },
];
